### ISSUE TITLE
POS integration

### ISSUE THREAD

**Issue by mariani70** [TransactilityInc/Selcom#1]
### Description
Selcom will use 2 different type of POS in terms of the message protocol, due to this we have to work on two diferent activities to integrate each type of POS

### Tasks

- [ ]  Pipe separated string
- [ ]  ISO based POS
- [ ] POS Acquiring for Mastercard and Visa
